//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGestionParcours.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGestionParcoursEntities : DbContext
    {
        public DBGestionParcoursEntities()
            : base("name=DBGestionParcoursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chapitre> Chapitre { get; set; }
        public virtual DbSet<EvaluationModule> EvaluationModule { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Parcours> Parcours { get; set; }
        public virtual DbSet<Realisation> Realisation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
