//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGestionParcours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Chapitre = new HashSet<Chapitre>();
            this.EvaluationModule = new HashSet<EvaluationModule>();
            this.Realisation = new HashSet<Realisation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idParcours { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> NoteActuelle { get; set; }
        public Nullable<System.DateTime> DateDerniereEval { get; set; }
        public string Logo { get; set; }
        public string infos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapitre> Chapitre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationModule> EvaluationModule { get; set; }
        public virtual Parcours Parcours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realisation> Realisation { get; set; }
    }
}
